name: Access sleep-time URL every 5 minutes

on:
  schedule:
    # Every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  curl-job:
    runs-on: ubuntu-latest

    steps:
    - name: Curl to sleep-time URL
      run: |
        curl -X GET "https://edu-open-4step.glitch.me/sleep-time" -o result.txt
    - name: Upload result to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: result
        path: result.txt
